[package]
name = "blokus_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "blokus_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
numpy = "0.27"
